import { IndexData, ProjectData } from '../types';

export const mockAllProjectMetas: IndexData = {
  time: 1739172240513,
  repos: [
    {
      name: 'nacos',
      text: 'Nacos',
      description: '一个更易于构建云原生应用的动态服务发现、配置管理和服务管理平台',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/nacos',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/mirrors/Nacos',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://nacos.io/zh-cn/docs/what-is-nacos.html',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://nacos.io/zh-cn/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/nacos.png',
    },
    {
      name: 'canal',
      text: 'Canal',
      description: '阿里巴巴 MySQL binlog 增量订阅&消费组件',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/canal',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/mirrors/canal',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://github.com/alibaba/canal/wiki',
          text: '文档地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/canal.png',
    },
    {
      name: 'sca',
      text: 'Spring Cloud Alibaba',
      description:
        'Spring Cloud Alibaba provides a one-stop solution for application development for the distributed solutions of Alibaba middleware.',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/spring-cloud-alibaba',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/mirrors/Spring-Cloud-Alibaba',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://spring.io/projects/spring-cloud-alibaba',
          text: '文档地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/sca.png',
    },
    {
      name: 'seata',
      text: 'Apache Seata',
      description:
        'Seata is an easy-to-use, high-performance, open source distributed transaction solution.',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/apache/incubator-seata',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/seata-io/seata',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://seata.apache.org/zh-cn/docs/overview/what-is-seata/',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://seata.apache.org/zh-cn/index.html',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/seata.png',
    },
    {
      name: 'sentinel',
      text: 'Sentinel',
      description:
        'A powerful flow control component enabling reliability, resilience and monitoring for microservices. (面向云原生微服务的高可用流控防护组件)',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/Sentinel',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/mirrors/Sentinel',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://sentinelguard.io/zh-cn/docs/introduction.html',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://sentinelguard.io/zh-cn/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/sentinel.png',
    },
    {
      name: 'opensergo',
      text: 'OpenSergo',
      description: 'Universal cloud-native microservice governance specification (微服务治理标准)',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/opensergo/',
          text: 'GitHub 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://opensergo.io/docs/what-is-opensergo/intro/',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://opensergo.io/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/opensergo.png',
    },
    {
      name: 'datax',
      text: 'DataX',
      description: 'DataX是阿里云DataWorks数据集成的开源版本',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/DataX',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/mirrors/DataX',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://github.com/alibaba/DataX/blob/master/userGuid.md',
          text: '文档地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/datax.png',
    },
    {
      name: 'lowcode_engine',
      text: 'Lowcode Engine',
      description:
        'An enterprise-class low-code technology stack with scale-out design / 一套面向扩展设计的企业级低代码技术体系',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/lowcode-engine',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/mirrors_alibaba/lowcode-engine',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://lowcode-engine.cn/site/docs/guide/quickStart/intro',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://lowcode-engine.cn',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/lowcode_engine.png',
    },
    {
      name: 'easyexcel',
      text: 'EasyExcel',
      description: '快速、简洁、解决大文件内存溢出的java处理Excel工具',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/easyexcel',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/mirrors/easyexcel',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://easyexcel.opensource.alibaba.com/docs/current/',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://easyexcel.opensource.alibaba.com/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/easyexcel.png',
    },
    {
      name: 'arthas',
      text: 'Arthas',
      description: 'Alibaba Java Diagnostic Tool Arthas/Alibaba Java 诊断利器 Arthas',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/arthas',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/arthas/arthas',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://arthas.aliyun.com/doc/',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://arthas.aliyun.com/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/arthas.png',
    },
    {
      name: 'sealer',
      text: 'Sealer',
      description:
        'Define and deliver your kube-cluster in a standard and easy way (Project under CNCF)',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/sealerio/sealer',
          text: 'GitHub 地址',
        },
        {
          type: 'documentUrl',
          url: 'http://sealer.cool/docs/introduction/introduction.html#introduction',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'http://sealer.cool/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/sealer.png',
    },
    {
      name: 'openyurt',
      text: 'OpenYurt',
      description: 'OpenYurt - Extending your native Kubernetes to edge(project under CNCF)',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/openyurtio/openyurt',
          text: 'GitHub 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://openyurt.io/docs/',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://openyurt.io/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/openyurt.png',
    },
    {
      name: 'ice',
      text: 'Ice',
      description:
        'ice.js: The Progressive App Framework Based On React（基于 React 的渐进式应用框架）',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/ice',
          text: 'GitHub 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://ice.work/docs/guide/about/',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://ice.work/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/ice.png',
    },
    {
      name: 'midway',
      text: 'MidwayJS',
      description:
        'A Node.js Serverless Framework for front-end/full-stack developers. Build the application for next decade. Works on AWS, Alibaba Cloud, Tencent Cloud and traditional VM/Container. Super easy integrate with React and Vue.',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/midwayjs/midway',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/mirrors/Midway',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://midwayjs.org/docs/intro',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://midwayjs.org/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/midway.png',
    },
    {
      name: 'havenask',
      text: 'Havenask',
      description:
        'Havenask 是阿里巴巴集团自研的搜索引擎，也是阿里巴巴内部广泛使用的大规模分布式检索系统，支持了包括淘宝、天猫、菜鸟、高德、饿了么、全球化在内整个阿里巴巴集团的搜索业务，为用户提供高性能、低成本、易用的搜索服务，同时具有灵活的定制和开发能力，支持算法快速迭代，帮助客户和开发者量身定做适合自身业务的智能搜索服务，助力业务增长。',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/havenask',
          text: 'GitHub 地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/havenask.png',
    },
    {
      name: 'modelscope',
      text: 'ModelScope',
      description:
        'ModelScope is committed to empowering a wide-spectrum of developers to leverage AI models from various domains. (致力于通过开放的社区合作，开源AI模型以及相关创新技术，推动基于模型即服务的生态繁荣发展。)',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/modelscope/modelscope',
          text: 'GitHub 地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/modelscope.png',
    },
    {
      name: 'polardb-pg',
      text: 'PolarDB-for-PostgreSQL',
      description: 'A cloud-native database based on PostgreSQL developed by Alibaba Cloud.',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/ApsaraDB/PolarDB-for-PostgreSQL',
          text: 'GitHub 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://apsaradb.github.io/PolarDB-for-PostgreSQL/zh/guide/#%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://apsaradb.github.io/PolarDB-for-PostgreSQL/zh/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/polardb-pg.png',
    },
    {
      name: 'polardb-x',
      text: 'PolarDB-X',
      description:
        'PolarDB-X is a cloud native distributed SQL Database designed for high concurrency, massive storage, complex querying scenarios.',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/polardb/polardbx-sql',
          text: 'GitHub 地址',
        },
        {
          type: 'giteeUrl',
          url: 'https://gitee.com/apsaradb/galaxysql',
          text: 'Gitee 地址',
        },
        {
          type: 'documentUrl',
          url: 'https://doc.polardbx.com/',
          text: '文档地址',
        },
        {
          type: 'officialUrl',
          url: 'https://www.polardbx.com/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/polardb-x.png',
    },
    {
      name: 'fluid',
      text: 'Fluid',
      description:
        'Fluid, elastic data abstraction and acceleration for BigData/AI applications in cloud. (Project under CNCF)',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/fluid-cloudnative/fluid',
          text: 'GitHub 地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/fluid.png',
    },
    {
      name: 'kubevela',
      text: 'KubeVela',
      description:
        "KubeVela is a modern application delivery platform that makes deploying and operating applications across today's hybrid, multi-cloud environments easier, faster and more reliable.",
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/kubevela/kubevela',
          text: 'GitHub 地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/foundations/linux_foundation/cncf/kubevela.png',
    },
    {
      name: 'higress',
      text: 'Higress',
      description: 'Next-generation Cloud Native Gateway | 下一代云原生网关',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba/higress',
          text: 'GitHub 地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/higress.png',
    },
    {
      name: 'fusion',
      text: 'Fusion Design',
      description:
        'An enterprise-level solution for building web products by improving designer-developer collaboration, product experience consistency, and development efficiency',
      urls: [
        {
          type: 'githubUrl',
          url: 'https://github.com/alibaba-fusion/next',
          text: 'GitHub 地址',
        },
        {
          type: 'officialUrl',
          url: 'https://fusion.design/',
          text: '官网地址',
        },
      ],
      logo: 'https://alibaba-openrank.oss-cn-hangzhou.aliyuncs.com/logos/companies/alibaba/fusion.png',
    },
  ],
};

export const mockNacosProjectData202501: ProjectData = {
  name: 'nacos',
  text: 'Nacos',
  details: [
    {
      l: 'KomachiSion',
      o: '13.31',
      a: 'https://avatars.githubusercontent.com/KomachiSion',
      r: '1',
      od: '0.20',
      rd: '0',
      i: true,
    },
    {
      l: 'github-actions[bot]',
      o: '3.24',
      a: 'https://avatars.githubusercontent.com/in/15368',
      r: '2',
      od: '0.91',
      rd: '2',
      b: true,
    },
    {
      l: 'Dario-s-j',
      o: '3.08',
      a: 'https://avatars.githubusercontent.com/Dario-s-j',
      r: '3',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'CZJCC',
      o: '2.45',
      a: 'https://avatars.githubusercontent.com/CZJCC',
      r: '4',
      od: '0.15',
      rd: '1',
    },
    {
      l: 'CLAassistant',
      o: '2.19',
      a: 'https://avatars.githubusercontent.com/CLAassistant',
      r: '5',
      od: '-0.03',
      rd: '1',
      b: true,
    },
    {
      l: 'Majidrazaee',
      o: '2.19',
      a: 'https://avatars.githubusercontent.com/Majidrazaee',
      r: '6',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'MatthewAden',
      o: '2.05',
      a: 'https://avatars.githubusercontent.com/MatthewAden',
      r: '7',
      od: '0.58',
      rd: '3',
    },
    {
      l: 'CherishCai',
      o: '1.87',
      a: 'https://avatars.githubusercontent.com/CherishCai',
      r: '8',
      od: '0.68',
      rd: '6',
    },
    {
      l: 'shiyiyue1102',
      o: '1.76',
      a: 'https://avatars.githubusercontent.com/shiyiyue1102',
      r: '9',
      od: '-1.11',
      rd: '-7',
      i: true,
    },
    {
      l: 'Aaron199',
      o: '1.56',
      a: 'https://avatars.githubusercontent.com/Aaron199',
      r: '10',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'wuyfee',
      o: '1.43',
      a: 'https://avatars.githubusercontent.com/wuyfee',
      r: '11',
      od: '-0.50',
      rd: '-4',
    },
    {
      l: 'CedarBetty',
      o: '1.26',
      a: 'https://avatars.githubusercontent.com/CedarBetty',
      r: '12',
      od: '0.94',
      rd: '40',
    },
    {
      l: 'heqingpan',
      o: '1.20',
      a: 'https://avatars.githubusercontent.com/heqingpan',
      r: '13',
      od: '-1.55',
      rd: '-10',
    },
    {
      l: 'misakacoder',
      o: '1.19',
      a: 'https://avatars.githubusercontent.com/misakacoder',
      r: '14',
      od: '-0.12',
      rd: '-1',
    },
    {
      l: 'dependabot[bot]',
      o: '1.11',
      a: 'https://avatars.githubusercontent.com/in/29110',
      r: '15',
      od: '0.82',
      rd: '64',
      b: true,
    },
    {
      l: 'a981008',
      o: '0.95',
      a: 'https://avatars.githubusercontent.com/a981008',
      r: '16',
      od: '0.60',
      rd: '30',
    },
    {
      l: 'leyou240',
      o: '0.85',
      a: 'https://avatars.githubusercontent.com/leyou240',
      r: '17',
      od: '0.73',
      rd: '153',
    },
    {
      l: 'mawen12',
      o: '0.83',
      a: 'https://avatars.githubusercontent.com/mawen12',
      r: '18',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'code-jar',
      o: '0.81',
      a: 'https://avatars.githubusercontent.com/code-jar',
      r: '19',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'codecov-commenter',
      o: '0.72',
      a: 'https://avatars.githubusercontent.com/codecov-commenter',
      r: '20',
      od: '-0.59',
      rd: '-8',
      b: true,
    },
    {
      l: 'Justinwins',
      o: '0.71',
      a: 'https://avatars.githubusercontent.com/Justinwins',
      r: '21',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'xpy01xpy',
      o: '0.70',
      a: 'https://avatars.githubusercontent.com/xpy01xpy',
      r: '22',
      od: '-0.14',
      rd: '-5',
    },
    {
      l: 'chinesecooly',
      o: '0.67',
      a: 'https://avatars.githubusercontent.com/chinesecooly',
      r: '23',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'dayuange123',
      o: '0.67',
      a: 'https://avatars.githubusercontent.com/dayuange123',
      r: '24',
      od: '0.02',
      rd: '0',
    },
    {
      l: 'tclxjing8-li',
      o: '0.66',
      a: 'https://avatars.githubusercontent.com/tclxjing8-li',
      r: '25',
      od: '0.27',
      rd: '16',
    },
    {
      l: 'njjnjjnjj',
      o: '0.62',
      a: 'https://avatars.githubusercontent.com/njjnjjnjj',
      r: '26',
      od: 'new',
      rd: 'new',
    },
    {
      l: '1926813494',
      o: '0.61',
      a: 'https://avatars.githubusercontent.com/1926813494',
      r: '27',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'lazhenyi',
      o: '0.60',
      a: 'https://avatars.githubusercontent.com/lazhenyi',
      r: '28',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'wtjperi2003',
      o: '0.59',
      a: 'https://avatars.githubusercontent.com/wtjperi2003',
      r: '29',
      od: '0.30',
      rd: '56',
    },
    {
      l: 'klllmxx',
      o: '0.56',
      a: 'https://avatars.githubusercontent.com/klllmxx',
      r: '30',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'binbin0325',
      o: '0.54',
      a: 'https://avatars.githubusercontent.com/binbin0325',
      r: '31',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'stone-98',
      o: '0.54',
      a: 'https://avatars.githubusercontent.com/stone-98',
      r: '32',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'fuhouyu',
      o: '0.50',
      a: 'https://avatars.githubusercontent.com/fuhouyu',
      r: '33',
      od: '0.29',
      rd: '96',
    },
    {
      l: 'zx900930',
      o: '0.49',
      a: 'https://avatars.githubusercontent.com/zx900930',
      r: '34',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'PterX',
      o: '0.45',
      a: 'https://avatars.githubusercontent.com/PterX',
      r: '35',
      od: '0.10',
      rd: '10',
    },
    {
      l: 'dxh9231028',
      o: '0.45',
      a: 'https://avatars.githubusercontent.com/dxh9231028',
      r: '36',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'cnzakii',
      o: '0.44',
      a: 'https://avatars.githubusercontent.com/cnzakii',
      r: '37',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'MoritzArena',
      o: '0.44',
      a: 'https://avatars.githubusercontent.com/MoritzArena',
      r: '38',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'Noe1017',
      o: '0.44',
      a: 'https://avatars.githubusercontent.com/Noe1017',
      r: '39',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'gyjx',
      o: '0.43',
      a: 'https://avatars.githubusercontent.com/gyjx',
      r: '40',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'zeyu-zh',
      o: '0.42',
      a: 'https://avatars.githubusercontent.com/zeyu-zh',
      r: '41',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'wentfar',
      o: '0.41',
      a: 'https://avatars.githubusercontent.com/wentfar',
      r: '42',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'zhouchunhai',
      o: '0.40',
      a: 'https://avatars.githubusercontent.com/zhouchunhai',
      r: '43',
      od: '0.30',
      rd: '149',
    },
    {
      l: 'liuyuchuan',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/liuyuchuan',
      r: '44',
      od: '0.25',
      rd: '130',
    },
    {
      l: 'cnsky1103',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/cnsky1103',
      r: '45',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'ITLZP',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/ITLZP',
      r: '46',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'slankka',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/slankka',
      r: '47',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'menghuan',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/menghuan',
      r: '48',
      od: '0.18',
      rd: '91',
    },
    {
      l: 'JacianZhu',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/JacianZhu',
      r: '49',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'nanlaogou',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/nanlaogou',
      r: '50',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'ldcsaa',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/ldcsaa',
      r: '51',
      od: '0.16',
      rd: '75',
    },
    {
      l: 'clcc2019',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/clcc2019',
      r: '52',
      od: '0.11',
      rd: '53',
    },
    {
      l: 'dannyxu2015',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/dannyxu2015',
      r: '53',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'hirolee88',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/hirolee88',
      r: '54',
      od: 'new',
      rd: 'new',
    },
    {
      l: '02maple',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/02maple',
      r: '55',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'oiooooio',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/oiooooio',
      r: '56',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'vicenteLorenzo',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/vicenteLorenzo',
      r: '57',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'tm2018',
      o: '0.36',
      a: 'https://avatars.githubusercontent.com/tm2018',
      r: '58',
      od: '-0.19',
      rd: '-31',
    },
    {
      l: 'zhwaaaaaa',
      o: '0.35',
      a: 'https://avatars.githubusercontent.com/zhwaaaaaa',
      r: '59',
      od: '-0.43',
      rd: '-40',
    },
    {
      l: 'ziminghua',
      o: '0.34',
      a: 'https://avatars.githubusercontent.com/ziminghua',
      r: '60',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'lucky8987',
      o: '0.34',
      a: 'https://avatars.githubusercontent.com/lucky8987',
      r: '61',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'lfift',
      o: '0.33',
      a: 'https://avatars.githubusercontent.com/lfift',
      r: '62',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'wzshuang',
      o: '0.33',
      a: 'https://avatars.githubusercontent.com/wzshuang',
      r: '63',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'HUWEIWEI0105',
      o: '0.33',
      a: 'https://avatars.githubusercontent.com/HUWEIWEI0105',
      r: '64',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'davidfunn',
      o: '0.32',
      a: 'https://avatars.githubusercontent.com/davidfunn',
      r: '65',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'lnsane',
      o: '0.30',
      a: 'https://avatars.githubusercontent.com/lnsane',
      r: '66',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'medzeus2',
      o: '0.29',
      a: 'https://avatars.githubusercontent.com/medzeus2',
      r: '67',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'DoctorJackM',
      o: '0.29',
      a: 'https://avatars.githubusercontent.com/DoctorJackM',
      r: '68',
      od: '0.01',
      rd: '25',
    },
    {
      l: 'Sunrisea',
      o: '0.29',
      a: 'https://avatars.githubusercontent.com/Sunrisea',
      r: '69',
      od: '-1.38',
      rd: '-60',
    },
    {
      l: '52assert',
      o: '0.27',
      a: 'https://avatars.githubusercontent.com/52assert',
      r: '70',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'shalk',
      o: '0.27',
      a: 'https://avatars.githubusercontent.com/shalk',
      r: '71',
      od: '-0.21',
      rd: '-41',
    },
    {
      l: 'denzellin',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/denzellin',
      r: '72',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'Sarahbella4040',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/Sarahbella4040',
      r: '73',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'sweat123',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/sweat123',
      r: '74',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'GojoSensei1995',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/GojoSensei1995',
      r: '75',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'AsiaDeveloper',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/AsiaDeveloper',
      r: '76',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'moonnight0317',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/moonnight0317',
      r: '77',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'hzhxxx',
      o: '0.24',
      a: 'https://avatars.githubusercontent.com/hzhxxx',
      r: '78',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'mashuangwei',
      o: '0.24',
      a: 'https://avatars.githubusercontent.com/mashuangwei',
      r: '79',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'helloworld1612',
      o: '0.24',
      a: 'https://avatars.githubusercontent.com/helloworld1612',
      r: '80',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'fallsown',
      o: '0.24',
      a: 'https://avatars.githubusercontent.com/fallsown',
      r: '81',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'muzhi9018',
      o: '0.24',
      a: 'https://avatars.githubusercontent.com/muzhi9018',
      r: '82',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'yuanqinglong-code',
      o: '0.23',
      a: 'https://avatars.githubusercontent.com/yuanqinglong-code',
      r: '83',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'beanww',
      o: '0.23',
      a: 'https://avatars.githubusercontent.com/beanww',
      r: '84',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'stoneLee81',
      o: '0.23',
      a: 'https://avatars.githubusercontent.com/stoneLee81',
      r: '85',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'BinZl00',
      o: '0.23',
      a: 'https://avatars.githubusercontent.com/BinZl00',
      r: '86',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'liujunweipython',
      o: '0.23',
      a: 'https://avatars.githubusercontent.com/liujunweipython',
      r: '87',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'CKKLIN',
      o: '0.22',
      a: 'https://avatars.githubusercontent.com/CKKLIN',
      r: '88',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'yyqangular1',
      o: '0.22',
      a: 'https://avatars.githubusercontent.com/yyqangular1',
      r: '89',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'SoilChang',
      o: '0.20',
      a: 'https://avatars.githubusercontent.com/SoilChang',
      r: '90',
      od: '-0.25',
      rd: '-57',
    },
    {
      l: 'JianweiWang',
      o: '0.20',
      a: 'https://avatars.githubusercontent.com/JianweiWang',
      r: '91',
      od: '-0.11',
      rd: '-21',
    },
    {
      l: '1058098666',
      o: '0.20',
      a: 'https://avatars.githubusercontent.com/1058098666',
      r: '92',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'chenzfp',
      o: '0.20',
      a: 'https://avatars.githubusercontent.com/chenzfp',
      r: '93',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'hanxiantao',
      o: '0.19',
      a: 'https://avatars.githubusercontent.com/hanxiantao',
      r: '94',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'zhiqiang94',
      o: '0.19',
      a: 'https://avatars.githubusercontent.com/zhiqiang94',
      r: '95',
      od: '-0.26',
      rd: '-60',
    },
    {
      l: 'xiaoyang1012',
      o: '0.19',
      a: 'https://avatars.githubusercontent.com/xiaoyang1012',
      r: '96',
      od: '-0.12',
      rd: '-35',
    },
    {
      l: 'bwangll',
      o: '0.19',
      a: 'https://avatars.githubusercontent.com/bwangll',
      r: '97',
      od: '-0.11',
      rd: '-24',
    },
    {
      l: 'mivljack',
      o: '0.19',
      a: 'https://avatars.githubusercontent.com/mivljack',
      r: '98',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'leopornorecio',
      o: '0.18',
      a: 'https://avatars.githubusercontent.com/leopornorecio',
      r: '99',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'saytesnake',
      o: '0.18',
      a: 'https://avatars.githubusercontent.com/saytesnake',
      r: '100',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'wick-z',
      o: '0.18',
      a: 'https://avatars.githubusercontent.com/wick-z',
      r: '101',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'TomcatMoment',
      o: '0.15',
      a: 'https://avatars.githubusercontent.com/TomcatMoment',
      r: '102',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'w6et',
      o: '0.14',
      a: 'https://avatars.githubusercontent.com/w6et',
      r: '103',
      od: '0.02',
      rd: '75',
    },
    {
      l: 'xodn',
      o: '0.13',
      a: 'https://avatars.githubusercontent.com/xodn',
      r: '104',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'Myheartwilgn',
      o: '0.13',
      a: 'https://avatars.githubusercontent.com/Myheartwilgn',
      r: '105',
      od: '-0.29',
      rd: '-69',
    },
    {
      l: 'MajorHe1',
      o: '0.12',
      a: 'https://avatars.githubusercontent.com/MajorHe1',
      r: '106',
      od: '-0.18',
      rd: '-34',
    },
    {
      l: 'hhf296095496',
      o: '0.12',
      a: 'https://avatars.githubusercontent.com/hhf296095496',
      r: '107',
      od: 'new',
      rd: 'new',
    },
  ],
};

export const mockNacosProjectData2025: ProjectData = {
  name: 'nacos',
  text: 'Nacos',
  details: [
    {
      l: 'KomachiSion',
      o: '13.31',
      a: 'https://avatars.githubusercontent.com/KomachiSion',
      r: '1',
      od: '-172.69',
      rd: '0',
      i: true,
    },
    {
      l: 'github-actions[bot]',
      o: '3.24',
      a: 'https://avatars.githubusercontent.com/in/15368',
      r: '2',
      od: '-3.86',
      rd: '12',
      b: true,
    },
    {
      l: 'Dario-s-j',
      o: '3.08',
      a: 'https://avatars.githubusercontent.com/Dario-s-j',
      r: '3',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'CZJCC',
      o: '2.45',
      a: 'https://avatars.githubusercontent.com/CZJCC',
      r: '4',
      od: '-6.77',
      rd: '7',
    },
    {
      l: 'CLAassistant',
      o: '2.19',
      a: 'https://avatars.githubusercontent.com/CLAassistant',
      r: '5',
      od: '-36.07',
      rd: '-3',
      b: true,
    },
    {
      l: 'Majidrazaee',
      o: '2.19',
      a: 'https://avatars.githubusercontent.com/Majidrazaee',
      r: '6',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'MatthewAden',
      o: '2.05',
      a: 'https://avatars.githubusercontent.com/MatthewAden',
      r: '7',
      od: '-2.10',
      rd: '17',
    },
    {
      l: 'CherishCai',
      o: '1.87',
      a: 'https://avatars.githubusercontent.com/CherishCai',
      r: '8',
      od: '-10.30',
      rd: '1',
    },
    {
      l: 'shiyiyue1102',
      o: '1.76',
      a: 'https://avatars.githubusercontent.com/shiyiyue1102',
      r: '9',
      od: '-13.88',
      rd: '-3',
      i: true,
    },
    {
      l: 'Aaron199',
      o: '1.56',
      a: 'https://avatars.githubusercontent.com/Aaron199',
      r: '10',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'wuyfee',
      o: '1.43',
      a: 'https://avatars.githubusercontent.com/wuyfee',
      r: '11',
      od: '-4.61',
      rd: '8',
    },
    {
      l: 'CedarBetty',
      o: '1.26',
      a: 'https://avatars.githubusercontent.com/CedarBetty',
      r: '12',
      od: '0.94',
      rd: '557',
    },
    {
      l: 'heqingpan',
      o: '1.20',
      a: 'https://avatars.githubusercontent.com/heqingpan',
      r: '13',
      od: '-33.54',
      rd: '-10',
    },
    {
      l: 'misakacoder',
      o: '1.19',
      a: 'https://avatars.githubusercontent.com/misakacoder',
      r: '14',
      od: '-3.66',
      rd: '9',
    },
    {
      l: 'dependabot[bot]',
      o: '1.11',
      a: 'https://avatars.githubusercontent.com/in/29110',
      r: '15',
      od: '-7.01',
      rd: '-3',
      b: true,
    },
    {
      l: 'a981008',
      o: '0.95',
      a: 'https://avatars.githubusercontent.com/a981008',
      r: '16',
      od: '-0.07',
      rd: '100',
    },
    {
      l: 'leyou240',
      o: '0.85',
      a: 'https://avatars.githubusercontent.com/leyou240',
      r: '17',
      od: '0.08',
      rd: '150',
    },
    {
      l: 'mawen12',
      o: '0.83',
      a: 'https://avatars.githubusercontent.com/mawen12',
      r: '18',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'code-jar',
      o: '0.81',
      a: 'https://avatars.githubusercontent.com/code-jar',
      r: '19',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'codecov-commenter',
      o: '0.72',
      a: 'https://avatars.githubusercontent.com/codecov-commenter',
      r: '20',
      od: '-30.42',
      rd: '-16',
      b: true,
    },
    {
      l: 'Justinwins',
      o: '0.71',
      a: 'https://avatars.githubusercontent.com/Justinwins',
      r: '21',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'xpy01xpy',
      o: '0.70',
      a: 'https://avatars.githubusercontent.com/xpy01xpy',
      r: '22',
      od: '-5.24',
      rd: '-2',
    },
    {
      l: 'dayuange123',
      o: '0.67',
      a: 'https://avatars.githubusercontent.com/dayuange123',
      r: '23',
      od: '-0.29',
      rd: '100',
    },
    {
      l: 'chinesecooly',
      o: '0.67',
      a: 'https://avatars.githubusercontent.com/chinesecooly',
      r: '24',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'tclxjing8-li',
      o: '0.66',
      a: 'https://avatars.githubusercontent.com/tclxjing8-li',
      r: '25',
      od: '0.27',
      rd: '422',
    },
    {
      l: 'njjnjjnjj',
      o: '0.62',
      a: 'https://avatars.githubusercontent.com/njjnjjnjj',
      r: '26',
      od: 'new',
      rd: 'new',
    },
    {
      l: '1926813494',
      o: '0.61',
      a: 'https://avatars.githubusercontent.com/1926813494',
      r: '27',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'lazhenyi',
      o: '0.60',
      a: 'https://avatars.githubusercontent.com/lazhenyi',
      r: '28',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'wtjperi2003',
      o: '0.59',
      a: 'https://avatars.githubusercontent.com/wtjperi2003',
      r: '29',
      od: '0.30',
      rd: '659',
    },
    {
      l: 'klllmxx',
      o: '0.56',
      a: 'https://avatars.githubusercontent.com/klllmxx',
      r: '30',
      od: '-0.16',
      rd: '153',
    },
    {
      l: 'binbin0325',
      o: '0.54',
      a: 'https://avatars.githubusercontent.com/binbin0325',
      r: '31',
      od: '-9.91',
      rd: '-21',
    },
    {
      l: 'stone-98',
      o: '0.54',
      a: 'https://avatars.githubusercontent.com/stone-98',
      r: '32',
      od: '-5.68',
      rd: '-14',
    },
    {
      l: 'fuhouyu',
      o: '0.50',
      a: 'https://avatars.githubusercontent.com/fuhouyu',
      r: '33',
      od: '-3.20',
      rd: '-5',
    },
    {
      l: 'zx900930',
      o: '0.49',
      a: 'https://avatars.githubusercontent.com/zx900930',
      r: '34',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'PterX',
      o: '0.45',
      a: 'https://avatars.githubusercontent.com/PterX',
      r: '35',
      od: '-1.39',
      rd: '19',
    },
    {
      l: 'dxh9231028',
      o: '0.45',
      a: 'https://avatars.githubusercontent.com/dxh9231028',
      r: '36',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'cnzakii',
      o: '0.44',
      a: 'https://avatars.githubusercontent.com/cnzakii',
      r: '37',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'MoritzArena',
      o: '0.44',
      a: 'https://avatars.githubusercontent.com/MoritzArena',
      r: '38',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'Noe1017',
      o: '0.44',
      a: 'https://avatars.githubusercontent.com/Noe1017',
      r: '39',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'gyjx',
      o: '0.43',
      a: 'https://avatars.githubusercontent.com/gyjx',
      r: '40',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'zeyu-zh',
      o: '0.42',
      a: 'https://avatars.githubusercontent.com/zeyu-zh',
      r: '41',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'wentfar',
      o: '0.41',
      a: 'https://avatars.githubusercontent.com/wentfar',
      r: '42',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'zhouchunhai',
      o: '0.40',
      a: 'https://avatars.githubusercontent.com/zhouchunhai',
      r: '43',
      od: '-0.99',
      rd: '38',
    },
    {
      l: 'cnsky1103',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/cnsky1103',
      r: '44',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'liuyuchuan',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/liuyuchuan',
      r: '45',
      od: '-0.21',
      rd: '216',
    },
    {
      l: 'ITLZP',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/ITLZP',
      r: '46',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'hirolee88',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/hirolee88',
      r: '47',
      od: 'new',
      rd: 'new',
    },
    {
      l: '02maple',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/02maple',
      r: '48',
      od: '0.13',
      rd: '836',
    },
    {
      l: 'dannyxu2015',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/dannyxu2015',
      r: '49',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'vicenteLorenzo',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/vicenteLorenzo',
      r: '50',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'menghuan',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/menghuan',
      r: '51',
      od: '0.18',
      rd: '1165',
    },
    {
      l: 'JacianZhu',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/JacianZhu',
      r: '52',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'nanlaogou',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/nanlaogou',
      r: '53',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'ldcsaa',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/ldcsaa',
      r: '54',
      od: '-0.14',
      rd: '251',
    },
    {
      l: 'oiooooio',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/oiooooio',
      r: '55',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'clcc2019',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/clcc2019',
      r: '56',
      od: '0.11',
      rd: '738',
    },
    {
      l: 'slankka',
      o: '0.37',
      a: 'https://avatars.githubusercontent.com/slankka',
      r: '57',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'tm2018',
      o: '0.36',
      a: 'https://avatars.githubusercontent.com/tm2018',
      r: '58',
      od: '-1.23',
      rd: '8',
    },
    {
      l: 'zhwaaaaaa',
      o: '0.35',
      a: 'https://avatars.githubusercontent.com/zhwaaaaaa',
      r: '59',
      od: '-2.87',
      rd: '-24',
    },
    {
      l: 'lucky8987',
      o: '0.34',
      a: 'https://avatars.githubusercontent.com/lucky8987',
      r: '60',
      od: '-0.59',
      rd: '68',
    },
    {
      l: 'ziminghua',
      o: '0.34',
      a: 'https://avatars.githubusercontent.com/ziminghua',
      r: '61',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'lfift',
      o: '0.33',
      a: 'https://avatars.githubusercontent.com/lfift',
      r: '62',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'wzshuang',
      o: '0.33',
      a: 'https://avatars.githubusercontent.com/wzshuang',
      r: '63',
      od: '-0.30',
      rd: '168',
    },
    {
      l: 'HUWEIWEI0105',
      o: '0.33',
      a: 'https://avatars.githubusercontent.com/HUWEIWEI0105',
      r: '64',
      od: '-0.34',
      rd: '147',
    },
    {
      l: 'davidfunn',
      o: '0.32',
      a: 'https://avatars.githubusercontent.com/davidfunn',
      r: '65',
      od: '0.04',
      rd: '642',
    },
    {
      l: 'lnsane',
      o: '0.30',
      a: 'https://avatars.githubusercontent.com/lnsane',
      r: '66',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'medzeus2',
      o: '0.29',
      a: 'https://avatars.githubusercontent.com/medzeus2',
      r: '67',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'DoctorJackM',
      o: '0.29',
      a: 'https://avatars.githubusercontent.com/DoctorJackM',
      r: '68',
      od: '0.01',
      rd: '666',
    },
    {
      l: 'Sunrisea',
      o: '0.29',
      a: 'https://avatars.githubusercontent.com/Sunrisea',
      r: '69',
      od: '-3.53',
      rd: '-42',
    },
    {
      l: '52assert',
      o: '0.27',
      a: 'https://avatars.githubusercontent.com/52assert',
      r: '70',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'shalk',
      o: '0.27',
      a: 'https://avatars.githubusercontent.com/shalk',
      r: '71',
      od: '-12.31',
      rd: '-63',
    },
    {
      l: 'denzellin',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/denzellin',
      r: '72',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'Sarahbella4040',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/Sarahbella4040',
      r: '73',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'sweat123',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/sweat123',
      r: '74',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'GojoSensei1995',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/GojoSensei1995',
      r: '75',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'AsiaDeveloper',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/AsiaDeveloper',
      r: '76',
      od: '-0.08',
      rd: '485',
    },
    {
      l: 'moonnight0317',
      o: '0.25',
      a: 'https://avatars.githubusercontent.com/moonnight0317',
      r: '77',
      od: '0.02',
      rd: '923',
    },
    {
      l: 'helloworld1612',
      o: '0.24',
      a: 'https://avatars.githubusercontent.com/helloworld1612',
      r: '78',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'hzhxxx',
      o: '0.24',
      a: 'https://avatars.githubusercontent.com/hzhxxx',
      r: '79',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'mashuangwei',
      o: '0.24',
      a: 'https://avatars.githubusercontent.com/mashuangwei',
      r: '80',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'muzhi9018',
      o: '0.24',
      a: 'https://avatars.githubusercontent.com/muzhi9018',
      r: '81',
      od: '0.15',
      rd: '1417',
    },
    {
      l: 'fallsown',
      o: '0.24',
      a: 'https://avatars.githubusercontent.com/fallsown',
      r: '82',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'beanww',
      o: '0.23',
      a: 'https://avatars.githubusercontent.com/beanww',
      r: '83',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'yuanqinglong-code',
      o: '0.23',
      a: 'https://avatars.githubusercontent.com/yuanqinglong-code',
      r: '84',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'stoneLee81',
      o: '0.23',
      a: 'https://avatars.githubusercontent.com/stoneLee81',
      r: '85',
      od: '-0.07',
      rd: '552',
    },
    {
      l: 'BinZl00',
      o: '0.23',
      a: 'https://avatars.githubusercontent.com/BinZl00',
      r: '86',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'liujunweipython',
      o: '0.23',
      a: 'https://avatars.githubusercontent.com/liujunweipython',
      r: '87',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'CKKLIN',
      o: '0.22',
      a: 'https://avatars.githubusercontent.com/CKKLIN',
      r: '88',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'yyqangular1',
      o: '0.22',
      a: 'https://avatars.githubusercontent.com/yyqangular1',
      r: '89',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'SoilChang',
      o: '0.20',
      a: 'https://avatars.githubusercontent.com/SoilChang',
      r: '90',
      od: '-0.25',
      rd: '263',
    },
    {
      l: 'JianweiWang',
      o: '0.20',
      a: 'https://avatars.githubusercontent.com/JianweiWang',
      r: '91',
      od: '-2.34',
      rd: '-47',
    },
    {
      l: '1058098666',
      o: '0.20',
      a: 'https://avatars.githubusercontent.com/1058098666',
      r: '92',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'chenzfp',
      o: '0.20',
      a: 'https://avatars.githubusercontent.com/chenzfp',
      r: '93',
      od: '-0.03',
      rd: '900',
    },
    {
      l: 'zhiqiang94',
      o: '0.19',
      a: 'https://avatars.githubusercontent.com/zhiqiang94',
      r: '94',
      od: '-0.26',
      rd: '266',
    },
    {
      l: 'xiaoyang1012',
      o: '0.19',
      a: 'https://avatars.githubusercontent.com/xiaoyang1012',
      r: '95',
      od: '-0.43',
      rd: '147',
    },
    {
      l: 'bwangll',
      o: '0.19',
      a: 'https://avatars.githubusercontent.com/bwangll',
      r: '96',
      od: '-3.51',
      rd: '-67',
    },
    {
      l: 'hanxiantao',
      o: '0.19',
      a: 'https://avatars.githubusercontent.com/hanxiantao',
      r: '97',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'mivljack',
      o: '0.19',
      a: 'https://avatars.githubusercontent.com/mivljack',
      r: '98',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'saytesnake',
      o: '0.18',
      a: 'https://avatars.githubusercontent.com/saytesnake',
      r: '99',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'leopornorecio',
      o: '0.18',
      a: 'https://avatars.githubusercontent.com/leopornorecio',
      r: '100',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'wick-z',
      o: '0.18',
      a: 'https://avatars.githubusercontent.com/wick-z',
      r: '101',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'TomcatMoment',
      o: '0.15',
      a: 'https://avatars.githubusercontent.com/TomcatMoment',
      r: '102',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'w6et',
      o: '0.14',
      a: 'https://avatars.githubusercontent.com/w6et',
      r: '103',
      od: '0.02',
      rd: '1314',
    },
    {
      l: 'xodn',
      o: '0.13',
      a: 'https://avatars.githubusercontent.com/xodn',
      r: '104',
      od: 'new',
      rd: 'new',
    },
    {
      l: 'Myheartwilgn',
      o: '0.13',
      a: 'https://avatars.githubusercontent.com/Myheartwilgn',
      r: '105',
      od: '-0.29',
      rd: '298',
    },
    {
      l: 'MajorHe1',
      o: '0.12',
      a: 'https://avatars.githubusercontent.com/MajorHe1',
      r: '106',
      od: '-1.05',
      rd: '-2',
    },
    {
      l: 'hhf296095496',
      o: '0.12',
      a: 'https://avatars.githubusercontent.com/hhf296095496',
      r: '107',
      od: 'new',
      rd: 'new',
    },
  ],
};
